### ISSUE TITLE
I couldn't get it to work 

### ISSUE THREAD

**Issue by chesse20** [TheNexusAvenger/Nexus-VR-Character-Model-Legacy#1]
i tried putting the script in mulitipile places and it keeps telling me something about the script having a infinite yeld possible and then the script doesn't work

**Comment by TheNexusAvenger** [comment]
Do you have a place file or any sort of repro steps?

**Comment by chesse20** [comment]
I just tried using my vr headset on your test place for the script. https://www.roblox.com/games/1502435445/Nexus-VR-Character-Model-Demo It did not work there either. I think your vr plugin might only work on microsoft mr or something becuase i have a vive and you probably couldn't get anyone to test on any other vr headset. Just my guess

**Comment by TheNexusAvenger** [comment]
I tested it with both an Oculus Rift and HTC Vive before, and both of them worked. I didn't use any API to pick which headsets work, and the Microsoft Mixed Reality headsets currently register as Vive.  Do you have the toggle in the menu enabled, and does Roblox launch as a normal VR character?

**Comment by chesse20** [comment]
what toggle in what menu? Everything looked the same as usual when i booted into vr when the vr player model script was in the game.

**Comment by TheNexusAvenger** [comment]
There is a VR toggle in the main ESC menu. Since a VR character loads, it should be on. Can I get a screenshot with the F9 console in VR?

**Comment by TheNexusAvenger** [comment]
Bit of an update: Someone was able to give me more clear repro steps. It may be on Roblox's end with VRService.VREnabled not being enabled when it is changed. I will be investigating more tomorrow when I am at the VR lab.

**Comment by TheNexusAvenger** [comment]
Should be fixed now. Added a while loop for 10 seconds that attempts to start the character, since it seems like VREnabled is false and Changed isn't firing.
