### ISSUE TITLE
Use Rojo for script organization

### ISSUE THREAD

**Issue by LPGhatguy** [TheNexusAvenger/Nexus-VR-Character-Model-Legacy#3]
Your README mentions that there isn't a good way to store an instance tree on GitHub.

You should consider using my project, [Rojo](https://github.com/LPGhatguy/rojo), which provides a good way to version control scripts and simple instances by putting them onto the filesystem and syncing them  into Studio in real-time!

**Comment by TheNexusAvenger** [comment]
I put the code up to be used as a reference and for tracking bugs. Not really looking into methods of version control from outside of Roblox.
